#!/usr/bin/env python3
"""
Regenerate docs/readme/main.svg, the consolidated SVG that drives README.md.

The README is a single dark, on-brand image (hero + CTAs + screenshot)
that hands GitHub visitors off to https://tabflow.app/. To stay seamless across
GitHub light & dark themes, every visible element is baked into one SVG —
including the hero screenshot, embedded as a base64 JPG.

What this script does:
  1. Reads a source screenshot (default: docs/readme/screenshot-source.webp).
  2. Re-encodes it to a 1800-wide quality-86 JPG via ImageMagick.
  3. Embeds it as base64 in the SVG template defined below.
  4. Writes the result to docs/readme/main.svg.

This script is intentionally NOT wired into CI. Run it manually after updating
the source screenshot or the SVG layout.

Usage:
  scripts/build_readme_svg.py [PATH_TO_SCREENSHOT]

  Without an argument, reads docs/readme/screenshot-source.webp.
  Pass a path to override (any format ImageMagick can read: webp, png, jpg).

Requires: python3, ImageMagick (`magick`).
"""

import base64
import os
import subprocess
import sys
import tempfile

REPO_ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.realpath(__file__)), '..'))
DEFAULT_SOURCE = os.path.join(REPO_ROOT, 'docs', 'readme', 'screenshot-source.webp')
DEFAULT_ICON = os.path.join(REPO_ROOT, 'resources', 'icons', 'app', 'app.iconset', 'icon_512x512@2x.png')
OUTPUT_PATH = os.path.join(REPO_ROOT, 'docs', 'readme', 'main.svg')


def encode_screenshot(input_path: str) -> str:
    """Re-encode the source image to 1800-wide quality-86 JPG, return base64."""
    with tempfile.NamedTemporaryFile(suffix='.jpg', delete=False) as tmp:
        tmp_path = tmp.name
    try:
        try:
            subprocess.run(
                ['magick', input_path, '-resize', '1800x>', '-quality', '86', tmp_path],
                check=True,
            )
        except (FileNotFoundError, subprocess.CalledProcessError):
            subprocess.run(
                ['sips', '-s', 'format', 'jpeg', '-s', 'formatOptions', '86', '--resampleWidth', '1800', input_path, '--out', tmp_path],
                check=True,
            )
        with open(tmp_path, 'rb') as f:
            return base64.b64encode(f.read()).decode('ascii')
    finally:
        if os.path.exists(tmp_path):
            os.unlink(tmp_path)


def encode_icon() -> str:
    """Encode the brand app icon PNG to base64."""
    with open(DEFAULT_ICON, 'rb') as f:
        return base64.b64encode(f.read()).decode('ascii')


def build_svg(screenshot_b64: str, icon_b64: str) -> str:
    """
    Build the SVG. Layout (y coordinates inside a 900x895 viewBox):
       50 - 194 : icon (144x144, vertically centered with the title+tagline stack)
      120       : "TabFlow" title baseline
      158       : tagline baseline
      220 - 276 : CTA #1
      310 - 771 : screenshot (820x461, rounded corners)
      805 - 861 : CTA #2

    Gradients (matching the website's _buttons.scss exactly):
      - CTA pill : 36deg, 150px period, animated 14s (one full horizontal period)
    """
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<!--
  AUTOGENERATED by scripts/build_readme_svg.py — do not edit by hand.
-->
<svg xmlns="http://www.w3.org/2000/svg" width="900" height="895" viewBox="0 0 900 895">
  <defs>
    <linearGradient id="bg" x1="0%" y1="0%" x2="0%" y2="100%">
      <stop offset="0%" stop-color="#13132a"/>
      <stop offset="40%" stop-color="#0f0f24"/>
      <stop offset="100%" stop-color="#0a0a1a"/>
    </linearGradient>
    <radialGradient id="glow1" cx="50%" cy="6%" r="40%">
      <stop offset="0%" stop-color="#4488ff" stop-opacity="0.10"/>
      <stop offset="100%" stop-color="#0a0a1a" stop-opacity="0"/>
    </radialGradient>
    <radialGradient id="glow2" cx="50%" cy="40%" r="30%">
      <stop offset="0%" stop-color="#8F47EB" stop-opacity="0.08"/>
      <stop offset="100%" stop-color="#0a0a1a" stop-opacity="0"/>
    </radialGradient>

    <linearGradient id="ctaGrad"
      x1="0" y1="121.353" x2="88.167" y2="0"
      gradientUnits="userSpaceOnUse"
      spreadMethod="repeat">
      <stop offset="0" stop-color="#FF4488"/>
      <stop offset="0.333" stop-color="#4488ff"/>
      <stop offset="0.667" stop-color="#66CCFF"/>
      <stop offset="1" stop-color="#FF4488"/>
      <animateTransform attributeName="gradientTransform" type="translate"
        values="0,0; -255.267,0" dur="14s" repeatCount="indefinite"/>
    </linearGradient>

    <filter id="ctaShadow" x="-10%" y="-30%" width="120%" height="160%">
      <feDropShadow dx="0" dy="1" stdDeviation="1" flood-color="#000000" flood-opacity="0.25"/>
    </filter>

    <linearGradient id="iconCardA" x1="50%" x2="50%" y1="0%" y2="100%">
      <stop stop-color="#d619ac"/>
      <stop offset="1" stop-color="#d0224c"/>
    </linearGradient>
    <linearGradient id="iconCardB" x1="50%" x2="50%" y1="0%" y2="100%">
      <stop stop-color="#1ddfdf"/>
      <stop offset="1" stop-color="#1d8cdc"/>
    </linearGradient>
    <linearGradient id="iconCardC" x1="50%" x2="50%" y1="0%" y2="100%">
      <stop stop-color="#161386"/>
      <stop offset="1" stop-color="#0a093d"/>
    </linearGradient>
    <clipPath id="screenshotClip">
      <rect x="40" y="310" width="820" height="461" rx="14"/>
    </clipPath>
  </defs>

  <rect width="900" height="895" fill="url(#bg)"/>
  <rect width="900" height="895" fill="url(#glow1)"/>
  <rect width="900" height="895" fill="url(#glow2)"/>

  <g fill="#ffffff">
    <circle cx="60" cy="40" r="0.9" opacity="0.55"/>
    <circle cx="135" cy="80" r="0.6" opacity="0.35"/>
    <circle cx="200" cy="30" r="1.1" opacity="0.45"/>
    <circle cx="42" cy="160" r="0.5" opacity="0.3"/>
    <circle cx="170" cy="180" r="1" opacity="0.5"/>
    <circle cx="50" cy="240" r="0.6" opacity="0.4"/>
    <circle cx="120" cy="280" r="0.7" opacity="0.45"/>
    <circle cx="80" cy="290" r="0.9" opacity="0.5"/>
    <circle cx="700" cy="35" r="0.6" opacity="0.4"/>
    <circle cx="780" cy="80" r="1" opacity="0.5"/>
    <circle cx="840" cy="40" r="0.7" opacity="0.45"/>
    <circle cx="860" cy="170" r="0.6" opacity="0.35"/>
    <circle cx="730" cy="220" r="0.9" opacity="0.5"/>
    <circle cx="820" cy="280" r="0.5" opacity="0.3"/>
    <circle cx="870" cy="290" r="0.7" opacity="0.45"/>
    <circle cx="450" cy="22" r="0.5" opacity="0.3"/>
    <circle cx="60" cy="795" r="0.8" opacity="0.45"/>
    <circle cx="120" cy="855" r="0.5" opacity="0.3"/>
    <circle cx="180" cy="835" r="0.7" opacity="0.4"/>
    <circle cx="780" cy="785" r="0.6" opacity="0.4"/>
    <circle cx="840" cy="855" r="0.7" opacity="0.45"/>
    <circle cx="730" cy="835" r="0.5" opacity="0.3"/>
    <circle cx="40" cy="865" r="0.6" opacity="0.35"/>
    <circle cx="860" cy="795" r="0.5" opacity="0.3"/>
  </g>

  <g transform="translate(166 50)">
    <image href="data:image/png;base64,{icon_b64}" width="144" height="144"/>
  </g>

  <text x="330" y="120" font-family="-apple-system, BlinkMacSystemFont, 'SF Pro Display', 'Helvetica Neue', Helvetica, Arial, sans-serif" font-weight="700" font-size="56" fill="#ffffff" letter-spacing="-1.5">TabFlow</text>

  <text x="330" y="158" font-family="-apple-system, BlinkMacSystemFont, 'SF Pro Text', 'Helvetica Neue', Helvetica, Arial, sans-serif" font-weight="400" font-size="22" fill="#8888a8">See every window. Switch in an instant.</text>

  <g transform="translate(372 220)">
    <rect width="156" height="56" rx="28" fill="url(#ctaGrad)"/>
    <text x="78" y="36" text-anchor="middle" font-family="-apple-system, BlinkMacSystemFont, 'SF Pro Display', 'Helvetica Neue', Helvetica, Arial, sans-serif" font-weight="700" font-size="22" fill="#ffffff" filter="url(#ctaShadow)">Get TabFlow</text>
  </g>

  <image href="data:image/jpeg;base64,{screenshot_b64}" x="40" y="310" width="820" height="461" clip-path="url(#screenshotClip)" preserveAspectRatio="xMidYMid slice"/>

  <g transform="translate(372 805)">
    <rect width="156" height="56" rx="28" fill="url(#ctaGrad)"/>
    <text x="78" y="36" text-anchor="middle" font-family="-apple-system, BlinkMacSystemFont, 'SF Pro Display', 'Helvetica Neue', Helvetica, Arial, sans-serif" font-weight="700" font-size="22" fill="#ffffff" filter="url(#ctaShadow)">Get TabFlow</text>
  </g>
</svg>
'''


def main() -> None:
    src = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_SOURCE

    if not os.path.exists(src):
        print(f'error: screenshot not found at {src}', file=sys.stderr)
        print(f'pass a path as the first argument, or place the file at {DEFAULT_SOURCE}', file=sys.stderr)
        sys.exit(1)

    print(f'reading screenshot: {src}')
    b64 = encode_screenshot(src)
    icon_b64 = encode_icon()
    svg = build_svg(b64, icon_b64)

    with open(OUTPUT_PATH, 'w') as f:
        f.write(svg)

    print(f'wrote {os.path.getsize(OUTPUT_PATH):,} bytes to {OUTPUT_PATH}')


if __name__ == '__main__':
    main()
